
anella:
    admin:
        user: orambla
        email: oscar.rambla@i2cat.net
        sendmail: false

    app: # Anella app
        host: 0.0.0.0
        port: 9999

    database:
        host: 127.0.0.1
        port: 27017
        database_name: anella
        collections:
            config: config
            log: log
        database_repository: anella_repository

    auth: # Authentication service
        host: 84.88.76.5
        port: 8244
        eurecat: https://84.88.76.5:8244/1.0/LmpApiI2cat/
        oauth: keys/oauth_eurecat.json
    orch: # Orchestrator service manager
        host: 127.0.0.1
        port: 8082
        url: /orchestrator/api/v0.1/
    mail:
        from: admin.pi40@i2cat.net
        to: alfonso.egio@i2cat.net
        system: admin.pi40@i2cat.net
        owner: admin.pi40@i2cat.net
        developer: alfonso.egio@i2cat.net
        welcome: anella/mail_templates/welcome.txt
        ban: anella/mail_templates/ban.txt
        notify: anella/mail_templates/notify.txt
        account: keys/mail.json
        port: 587
        smtp: smtp.gmail.com
        subject: Registre de nou usuari
        body: Nou registre
    repository:
        path: /var/www/html/
        ip: http://dev.anella.i2cat.net:81/
        download: /home/ubuntu/tmp/
    tenor:
        host: localhost
        port: 4000
    errors:
        orchestrator_state: ORCHESTRATOR_GET_STATE
    keystone:
        url: http://dev.anella.i2cat.net:5000/v3/
        file: keys/keystone.json
        login: auth/tokens
        data_login: request/body_auth.json
        data_create_user: request/body_create_user.json
        data_patch_user: request/body_patch_user.json
        data_patch_password_user: request/body_patch_password_user.json
        data_change_password_user: request/body_change_password.json
        create_user: users
        project_name: PI40
