
anella:
    admin:
        user: orambla
        email: oscar.rambla@i2cat.net
        sendmail: false

    app: # Anella app
        host: 0.0.0.0
        port: 9999

    database:
        host: 127.0.0.1
        port: 27017
        database_name: anella
        collections:
            config: config
            log: log
        database_repository: anella_repository

    auth: # Authentication service
        host: 84.88.76.5
        port: 9763
        eurecat: http://84.88.76.5:9763/LmpApiI2cat/
    orch: # Orchestrator service manager
        host: 127.0.0.1
        port: 8082
        url: /orchestrator/api/v0.1/
    mail:
        from: anella.suport@gmail.com
        to: info@anellaindustrial.cat
        pass: i2catAnellaNexusII
        port: 587
        smtp: smtp.gmail.com
        subject: Registre de nou usuari
        body: Nou registre
    repository:
        path: /var/www/html/
        ip: http://dev.anella.i2cat.net:81/
        download: /home/ubuntu/tmp/
    tenor:
        host: localhost
        port: 4000
    errors:
        orchestrator_state: ORCHESTRATOR_GET_STATE