
anella:
    admin:
        user: orambla
        email: oscar.rambla@i2cat.net
        sendmail: false

    app: # Anella app
        host: 0.0.0.0
        port: 9999

    database:
        host: 127.0.0.1
        port: 27017
        database_name: anella
        collections:
            config: config
            log: log

    auth: # Authentication service
        host: 84.88.76.5
        port: 9763

    orch: # Orchestrator service manager
        host: 127.0.0.1
        port: 8082

