
anella:
    admin:
        user: orambla
        email: oscar.rambla@i2cat.net
        sendmail: false

    app: # Anella app
        host: 127.0.0.1
        port: 3010

    database:
        host: 127.0.0.1
        port: 27017
        database_name: anella-test
        collections:
            config: config
            log: log

    auth: # Authentication service
        host: 127.0.0.1
        port: 5672

    orch: # Orchestrator service manager
        host: anella.i2cat.net
        port: 8082
